<!DOCTYPE html>
<html>
    <head>
        <title>Terminos de uso</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>
        <script>
            $(function () {
                $("#header").load("Header.php");
                $("#footer").load("Footer.html");
            });
        </script> 
        <link href="../Estilos/Estilos.css" rel="stylesheet" type="text/css"/>
    </head>
    <body>
        <div id="header"></div> 
        <div class="content center width_90"style="margin-left:100px;">
            <h1> Terminos de <span class="color_rojo_general">Uso</span></h1>
                <div style="display: inline-block; text-align: left">
                <p><span class="SubHead">ACUERDO ENTRE EL USUARIO Y MusicAndSeek.com</span></p>
                <p>El sitio Web MusicAndSeek.com está compuesto por varias páginas Web operadas por MusicAndSeek.com.</p>
                <p>El sitio Web MusicAndSeek.com está disponible para tu uso bajo la condición de que tú aceptas sin excepciones ni modificaciones los términos, condiciones y advertencias contenidos en el presente documento. El sólo uso del sitio Web MusicAndSeek.com por parte tuya, constituye una prueba de tu aceptación a dichos términos, condiciones y advertencias.</p>
                <p><span class="SubHead">MODIFICACIONES A ESTOS TÉRMINOS Y CONDICIONES DE USO</span></p>
                <p>MusicAndSeek.com se reserva el derecho a modificar los términos, condiciones y advertencias bajo los cuales se ofrece el sitio Web MusicAndSeek.com, incluyendo, pero no limitado a, los precios y costes asociados por el uso del sitio Web MusicAndSeek.com.</p>
                <p><span class="SubHead">ENLACES A SITIOS DE TERCERAS PARTES</span></p>
                <p>El sitio Web MusicAndSeek.com puede contener enlaces a otros sitios Web (&#8220;sitios vinculados&#8221;). Los sitios vinculados no están bajo el control de MusicAndSeek.com y por lo tanto MusicAndSeek.com no es responsable de los contenidos de ningún sitio vinculado, incluyendo, aunque sin limitaciones, cualquier enlace contenido en un sitio vinculado, o cualquier cambio o actualización de un sitio vinculado. MusicAndSeek.com no es responsable de transmisiones en vivo o grabadas vía Web (&#8220;webcasting&#8221;) o cualquier otra forma de transmisión recibida desde cualquier sitio vinculado. MusicAndSeek.com lista estos enlaces para tu uso sólo como una facilidad para tu conveniencia, y la inclusión de estos enlaces no implica aprobación por parte de MusicAndSeek.com acerca de dichos sitios vinculados, ni asociación con sus operadores.</p>
                <p><span class="SubHead">EXCLUSIÓN DE USO PROHIBIDO O ILEGAL</span></p>
                <p>Como condición de tu uso del sitio Web MusicAndSeek.com, tú garantizas a MusicAndSeek.com que no utilizarás el sitio Web MusicAndSeek.com para propósitos ilegales o prohibidos por estos términos, condiciones y advertencias. No puedes utilizar el sitio Web MusicAndSeek.com de tal forma que pudiera dañar, deshabilitar, sobrecargar o deteriorar el sitio Web MusicAndSeek.com o interferir con el uso y provecho del sitio Web MusicAndSeek.com por terceras partes. No obtendrás ni intentarás obtener material o información utilizando otros medios distintos a aquellos que son expresa e intencionalmente ofrecidos a tal efecto en el sitio Web MusicAndSeek.com.</p>
                <p><span class="SubHead">USO DE SERVICIOS DE COMUNICACION</span></p>
                <p>El sitio Web MusicAndSeek.com puede contener servicios de aviso de mensajes (bulletin board services, BBS), áreas de chat, grupos de usuarios, foros de discusión, comunidades, páginas web personales, calendarios y/o otros servicios de mensajería o comunicación, diseñados para permitirte comunicarte con el público en general o con un grupo de personas (en adelante, &#8220;servicios de comunicación&#8221;). Tú aceptas utilizar los servicios de comunicación sólo para anunciar, enviar o recibir mensajes y material que sea apropiado y relativo al servicio de comunicación en particular. A modo de ejemplo, y no limitado a este detalle, tú aceptas que cuando utilices un servicio de comunicación, no podrás:</p>
                <ul>
                    <li>Difamar, abusar, acosar, acechar, amenazar o de alguna forma violar los derechos legales (como los derechos de privacidad) de otras personas.</li>
                    <li>Publicar, anunciar, subir, distribuir o diseminar ningún tema, nombre, material o información, que sea inapropiada, indecente, transgresora, difamatoria, obscena o ilegal.</li>
                    <li>Subir ficheros que contengan software u otro material protegido por leyes de propiedad intelectual (o derechos de privacidad) a menos que tú poseas la propiedad de tales materiales y/o controles los derechos respectivos, o hayas recibido el necesario consentimiento expreso de parte de quien corresponda.</li>
                    <li>Subir ficheros que contengan virus, o que estén corruptos, o cualquier otro software o programas que puedan dañar la operación del ordenador de otra persona.</li>
                    <li>Publicar u ofrecer a la venta o a la compra cualquier bien o servicio con propósitos comerciales, excepto en el caso que dicho servicio de comunicación permita específicamente ese tipo de mensajes.</li>
                    <li>Dirigir o reenviar encuestas, certámenes, cadenas de cartas o esquemas piramidales.</li>
                    <li>Bajar ficheros subidos por otro usuario de un servicio de comunicación cuando tú tuvieras o razonablemente debieras tener conocimiento de que no deban distribuirse legalmente de esa forma.</li>
                    <li>Falsificar o eliminar cualquier referencia al autor, referencia legal o advertencias o anuncios de propiedad o rótulos del origen o fuente del software u otro material contenidos en un fichero que se sube.</li>
                    <li>Restringir o inhibir a otros usuarios respecto de su normal uso y disfrute de los servicios de comunicación.</li>
                    <li>Violar cualesquiera códigos de conducta u otras guías que puedan aplicarse a un servicio de comunicación en particular.</li>
                    <li>Recolectar (o cualquier forma) información acerca de otros, incluyendo direcciones de correo electrónico, sin su consentimiento.</li>
                    <li>Violar leyes o regulaciones aplicables.</li>
                </ul>
                <p>MusicAndSeek.com no tiene la obligación de monitorear los servicios de comunicación. No obstante, MusicAndSeek.com se reserva el derecho de revisar los materiales anunciados en los servicios de comunicación y eliminarlos a su sola discreción. MusicAndSeek.com se reserva el derecho de denegarte el acceso a cualquiera o a todos los servicios de comunicación, en cualquier momento sin previo aviso y por la razón que sea.</p>
                <p>MusicAndSeek.com se reserva el derecho en cualquier momento a revelar información cuando sea necesario cumplir con cualesquiera leyes aplicables, regulaciones, procesos legales, pedidos del gobierno, o editar, denegar la publicación, o eliminar cualquier información o material, en su totalidad o en parte, a la sola discreción de MusicAndSeek.com.</p>
                <p>Sé siempre cuidadoso al dar cualquier información personal que te identifique o a tus hijos en todo servicio de comunicación. MusicAndSeek.com no controla ni aprueba el contenido, mensajes, o información encontrada en los servicios de comunicación y, por lo tanto, MusicAndSeek.com niega específicamente cualquier responsabilidad en relación con los servicios de comunicación y con cualesquiera acciones resultantes de tu participación en cualquier servicio de comunicación. Los administradores y anfitriones no son voceros autorizados de MusicAndSeek.com, y sus puntos de vista no necesariamente reflejan aquellos de MusicAndSeek.com.</p>
                <p>Los materiales subidos a un servicio de comunicación pueden estar sujetos a limitaciones en el uso, reproducción o difusión dispuestas por la persona que los haya subido. Tú eres responsable de cumplir con dichas limitaciones si bajas esos materiales.</p>
                <p><span class="SubHead">MATERIALES SUMINISTRADOS A MusicAndSeek.com O PUBLICADOS EN CUALQUIER SITIO WEB DE MusicAndSeek.com</span></p>
                <p>MusicAndSeek.com no reclama la propiedad de los materiales que tú suministres a MusicAndSeek.com (incluyendo comentarios y sugerencias) o anuncies, ofrezcas, subas, introduzcas, remitas o entregues a cualquier sitio Web de MusicAndSeek.com o sus servicios asociados (en adelante &#8220;entregas&#8221;). Sin embargo, al anunciar, publicar, subir, introducir, suministrar o entregar tus entregas, tú estás otorgando permiso a MusicAndSeek.com, a sus compañías afiliadas y licenciatarios, para utilizar dichas entregas en relación con la operación de sus respectivos negocios en internet, incluyendo, pero no limitado a, los derechos a copiar, distribuir, transmitir, mostrar públicamente, representar públicamente, reproducir, editar, traducir y dar nuevo formato a tu entrega, y a publicitar tu nombre en conexión con tu entrega.</p>
                <p>No se pagará ninguna compensación respecto al uso de tu entrega, tal como se describe aquí. MusicAndSeek.com no tiene ninguna obligación de anunciar, publicar o utilizar ninguna de las entregas que tú puedas suministrar, y puede eliminar cualquier entrega que hayas suministrado, en cualquier momento y a la sola discreción de MusicAndSeek.com.</p>
                <p>Por el sólo hecho de anunciar, subir, introducir, suministrar o entregar tus entregas, tú afirmas y garantizas que tú mismo eres el propietario o de alguna manera controlas todos los derechos de tu entrega, como se describe en esta sección; incluyendo, aunque no limitado a, todos los derechos necesarios para que tú suministres, anuncies, subas, introduzcas, entregues o remitas las entregas.</p>
                <p><span class="SubHead">LIMITACIÓN DE RESPONSABILIDAD</span></p>
                <p>LA INFORMACIÓN, SOFTWARE, PRODUCTOS Y SERVICIOS INCLUIDOS EN, O DISPONIBLES A TRAVÉS DEL SITIO WEB MusicAndSeek.com PUEDEN CONTENER INEXACTITUDES O ERRORES TIPOGRÁFICOS. PERIÓDICAMENTE SE REALIZAN MODIFICACIONES Y AGREGADOS A LA INFORMACIÓN AQUÍ CONTENIDA. MusicAndSeek.com Y/O SUS PROVEEDORES PUEDEN REALIZAR EN CUALQUIER MOMENTO MODIFICACIONES O MEJORAS AL SITIO WEB MusicAndSeek.com. LAS SUGERENCIAS QUE PUEDAN RECIBIRSE A TRAVÉS DEL SITIO WEB MusicAndSeek.com NO DEBERÍAN TENERSE EN CUENTA PARA LA TOMA DE DECISIONES PERSONALES, MÉDICAS, LEGALES O FINANCIERAS Y tú DEBERÍAS CONSULTAR A UN PROFESIONAL PARA EL ASESORAMIENTO ESPECÍFICO Y A LA MEDIDA DE TU SITUACIÓN.</p>
                <p>MusicAndSeek.com Y/O SUS PROVEEDORES, NO REALIZAN DECLARACIONES ACERCA DE LA CONVENIENCIA, CONFIABILIDAD, DISPONIBILIDAD, ACTUALIDAD, NI LA EXACTITUD DE LA INFORMACIÓN, SOFTWARE, PRODUCTOS, SERVICIOS Y GRÁFICOS CONTENIDOS EN EL SITIO WEB MusicAndSeek.com, SEA CUAL FUERE SU PROPÓSITO. DICHA INFORMACIÓN, SOFTWARE, PRODUCTOS, SERVICIOS Y GRÁFICOS RELACIONADOS, SE ENTREGAN &#8220;COMO SON&#8221;, SIN NINGÚN TIPO DE GARANTÍA O CONDICIÓN, DE ACUERDO AL MÁXIMO ALCANCE PERMITIDO POR LAS LEYES APLICABLES. MusicAndSeek.com Y/O SUS PROVEEDORES ANULAN POR ESTE MEDIO TODAS LAS GARANTÍAS Y CONDICIONES EN RELACIÓN CON ESTA INFORMACIÓN, SOFTWARE, PRODUCTOS, SERVICIOS Y GRÁFICOS RELACIONADOS, INCLUYENDO TODAS LAS GARANTÍAS O CONDICIONES IMPLÍCITAS (DERECHOS DE PROPIEDAD INTELECTUAL, DERECHOS DE AUTOR, COPYRIGHT) EN LA COMERCIALIZACIÓN y/o ADECUACIÓN A UN PROPÓSITO ESPECÍFICO.</p>
                <p>DE ACUERDO AL MÁXIMO ALCANCE PERMITIDO POR LAS LEYES APLICABLES, EN NINGÚN CASO MusicAndSeek.com y/o SUS PROVEEDORES SERÁN RESPONSABLES POR NINGÚN DAÑO DIRECTO, INDIRECTO, PUNITIVO, INCIDENTAL, ESPECIAL, CONSECUENTE, O CUALESQUIERA DAÑOS INCLUYENDO, AUNQUE NO LIMITADOS A, DAÑOS POR PÉRDIDA DE USO, DE DATOS O DE BENEFICIOS SURGIDOS DEL USO, O DE ALGUNA MANERA RELACIONADOS CON EL USO O RENDIMIENTO DEL SITIO WEB MusicAndSeek.com, CON LA DEMORA O LA IMPOSIBILIDAD DE USO DEL SITIO WEB MusicAndSeek.com O SUS SERVICIOS RELACIONADOS, LA PROVISIÓN O FALLA EN LA PROVISIÓN DE SERVICIOS, O POR CUALQUIER INFORMACIÓN, SOFTWARE, PRODUCTOS, SERVICIOS Y GRÁFICOS RELACIONADOS OBTENIDOS A TRAVÉS DEL SITIO WEB MusicAndSeek.com, O DE ALGUNA OTRA MANERA SURGIDOS A PARTIR DEL USO DEL SITIO WEB MusicAndSeek.com, YA SEA QUE SE BASEN EN UN CONTRATO, AGRAVIO, NEGLIGENCIA, ESTRICTA RESPONSABILIDAD, O CUALQUIER OTRA FORMA, AÚN CUANDO MusicAndSeek.com O CUALQUIERA DE SUS PROVEEDORES HAYAN SIDO AVISADOS ACERCA DE LA POSIBILIDAD DE DAÑOS. COMO EN ALGUNAS JURISDICCIONES NO SE PERMITE LA EXCLUSIÓN O LIMITACIÓN DE RESPONSABILIDAD POR DAÑOS INCIDENTALES O CONSECUENTES, PUEDE QUE LA LIMITACIÓN ARRIBA DETALLADA NO SE APLIQUE A TU CASO. SI NO ESTÁS SATISFECHO CON ALGUNA PARTE DEL SITIO WEB MusicAndSeek.com, O CON ALGUNO DE ESTOS TÉRMINOS DE USO, TU ÚNICA Y EXCLUSIVA SOLUCIÓN ES DEJAR DE UTILIZAR EL SITIO WEB MusicAndSeek.com.</p>
                <p>CONTACTO DEL SERVICIO: <a href="mailto:mondo@mondosonoro.com">mondo@mondosonoro.com</a></p>
                <p><span class="SubHead">FINALIZACIÓN DE SERVICIO / RESTRICCIÓN DE ACCESO</span></p>
                <p>MusicAndSeek.com se reserva el derecho, a su sola discreción, a finalizar tu acceso al sitio Web MusicAndSeek.com, así como a sus servicios relacionados o a cualquier parte de éstos, en cualquier momento y sin previa notificación.</p>
                <p><span class="SubHead">GENERAL</span></p>
                <p>De acuerdo al alcance máximo permitido por la ley, este acuerdo está gobernado por las leyes del estado de washington, U.S.A. y por consiguiente tú consientes como jurisdicción exclusiva y lugar donde se reúnen las cortes a king county, washington, U.S.A. en todas las disputas que surjan del uso o relativas al uso del sitio Web de MusicAndSeek.com. El uso del sitio Web de MusicAndSeek.com no está autorizado en jurisdicción alguna que no haga efectivas todas las provisiones de estos términos y condiciones, incluyendo, aunque no limitado a, las contenidas en este párrafo. Tú asientes que como resultado de este acuerdo o por el uso del sitio Web MusicAndSeek.com, no existe asociación, joint venture, relación de dependencia o empleo, o similar, entre tú y MusicAndSeek.com. El cumplimiento de este acuerdo por parte de MusicAndSeek.com está sujeto a las leyes vigentes y al proceso legal, y nada contenido en este acuerdo constituye una derogación al derecho de MusicAndSeek.com a obrar de acuerdo a los requisitos, solicitudes o imposiciones legales, del gobierno o de la corte, relacionados con tu uso del sitio Web MusicAndSeek.com, o a información recogida o suministrada a MusicAndSeek.com respecto de dicho uso. En caso que se determinara legalmente que alguna parte de este acuerdo fuera inválida o no exigible de acuerdo a la ley, incluyendo, aunque no limitado a, el rechazo de garantías y las limitaciones a la responsabilidad establecidas más arriba, entonces la cláusula inválida o no exigible se considerará sustituida por una cláusula válida y exigible, que se acerque lo más posible a la intención del texto original, y el resto del acuerdo continuará en efecto. Salvo lo especificado aquí, este acuerdo constituye el acuerdo completo entre el usuario y MusicAndSeek.com respecto del sitio Web MusicAndSeek.com y reemplaza a todas las comunicaciones y propuestas anteriores o contemporáneas, hayan sido éstas electrónicas, orales o escritas, entre el usuario y MusicAndSeek.com respecto del sitio Web MusicAndSeek.com. Una versión impresa de este acuerdo y de cualquier notificación enviada en forma electrónica, serán admitidas en procedimientos judiciales o administrativos basados en este acuerdo o relacionados con él, y tendrán el mismo alcance y estarán sujetas a las mismas condiciones que otros documentos y registros comerciales generados y mantenidos originalmente en forma impresa. Es el deseo expreso de las partes que este acuerdo y los documentos relacionados sean escritos en castellano.</p>
                <p><span class="SubHead">DERECHO DE PROPIEDAD INTELECTUAL Y COPYRIGHT</span></p>
                <p>Todos los contenidos del sitio Web MusicAndSeek.com son: Copyright 2009 by Mondosonoro y/o sus proveedores. Todos los derechos han sido reservados.</p>
                <p><span class="SubHead">MARCAS COMERCIALES</span></p>
                <p>Los nombres de compañías y productos reales mencionados aquí pueden ser marcas comerciales de sus respectivos propietarios.</p>
                <p>Los nombres usados en ejemplos de compañías, organizaciones, productos, personas y eventos descritos aquí son ficticios. No debe asociarse o inferirse relación alguna con ninguna compañía, organización, producto, persona o evento reales, a menos que sea explícitamente establecido en tales términos.</p>
                <p>Cualesquiera derechos no expresamente otorgados aquí son reservados.</p>
                <p><span class="SubHead">NOTIFICACIONES Y PROCEDIMIENTO DE RECLAMOS DE VIOLACIÓN A LOS DERECHOS DE PROPIEDAD INTELECTUAL Y COPYRIGHT</span></p>
                <p>Procediendo de acuerdo al title 17, united states code, section 512(c)(2), las notificaciones de reclamos a violaciones a los derechos de propiedad intelectual bajo la ley de copyright de los estados unidos, deben ser enviados al agente designado del proveedor de servicios. TODA PETICION QUE NO SEA RELEVANTE AL PROCEDIMIENTO NO RECIBIRÁ RESPUESTA. Lee las notificaciones y procedimiento de reclamos de violación a los derechos de propiedad intelectual y copyright.</p>
            </div>   
        </div>        

        <div id="footer"></div>
    </body>
</html>
